// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
using System.Reflection;

public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver(Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location));
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void LogandoNoSistema() {
    driver.Navigate().GoToUrl("https://localhost:44309/");
    driver.Manage().Window.Size = new System.Drawing.Size(1348, 818);
    driver.FindElement(By.LinkText("Login")).Click();
    driver.FindElement(By.Id("Email")).Click();
    driver.FindElement(By.Id("Email")).SendKeys("william@email.com");
    driver.FindElement(By.Id("Senha")).SendKeys("senha01");
    driver.FindElement(By.Id("Senha")).SendKeys(Keys.Enter);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.Close();
  }
}
